# Generated by Django 2.2.4 on 2019-08-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='state',
            new_name='state_name',
        ),
    ]
